name = "SwarmMakie"
uuid = "0b1c068e-6a84-4e66-8136-5c95cafa83ed"
version = "0.1.5"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>", "Jacob Zelko <jacobszelko@gmail.com>", "Michael Krabbe Borregaard <mkborregaard@snm.ku.dk>", "and contributors"]

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"

[extensions]
AlgebraOfGraphicsExt = "AlgebraOfGraphics"

[compat]
AlgebraOfGraphics = "0.9.5, 0.10, 0.11"
KernelDensity = "0.6"
Makie = "0.20, 0.21, 0.22, 0.23, 0.24"
StableRNGs = "1.0.4"
StatsBase = "0.34"
julia = "1.9"
